### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by khumnath** [sidbelbase/nepali-datetime-applet#1]
from: can't read /var/mail/main.nepali
from: can't read /var/mail/main.english
from: can't read /var/mail/time
/home/computebox/Documents/github/nepali-datetime-applet/main.py: 5: /home/computebox/Documents/github/nepali-datetime-applet/main.py: True: not found
/home/computebox/Documents/github/nepali-datetime-applet/main.py: 9: /home/computebox/Documents/github/nepali-datetime-applet/main.py: Syntax error: "(" unexpected

**Comment by sarojbelbase** [comment]
What's the python version you're running? It works with python 3. I tested it again, it works fine & I also added installation procedure, be sure to add a **virtual environment** as described there. Let me know if that solves it.

The error logs show nothing like python, how does it not recognize it's the builtin boolean syntax `True`? Please check once again.

**Comment by khumnath** [comment]
Let me check

**Comment by khumnath** [comment]
working now.
![Screen Capture_select-area_20200711194629](https://user-images.githubusercontent.com/50103558/87222558-705c1f00-c3af-11ea-8b9f-99d9436210a1.png)
